import Vue from 'vue'
import 'element-ui/lib/theme-chalk/index.css'
import { TabPane, Tabs, MessageBox, Tooltip, Message, Button, Select, Menu, MenuItem, Submenu, Table, TableColumn, Input, Pagination, Option, Dialog, Form, FormItem, Container, Aside, Main } from 'element-ui'

Vue.use(TabPane)
Vue.use(Tabs)
Vue.component(MessageBox)
Vue.use(Tooltip)
Vue.component(Message)
Vue.use(Button)
Vue.use(Select)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Input)
Vue.use(Pagination)
Vue.use(Option)
Vue.use(Dialog)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Container)
Vue.use(Main)
Vue.use(Aside)
